# 날씨 데이터

In [9]:
import pandas as pd

### 날씨 데이터 확인

In [10]:
weather_df = pd.read_csv('./data/weather_2016_2025.csv', encoding='cp949')

In [11]:
weather_df.info()
weather_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 348870 entries, 0 to 348869
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   지점                348870 non-null  int64
 1   지점명               348870 non-null  str
 2   일시                348870 non-null  str
 3   평균기온(°C)          348373 non-null  float64
 4   최저기온(°C)          348716 non-null  float64
 5   최고기온(°C)          348722 non-null  float64
 6   강수 계속시간(hr)       33584 non-null   float64
 7   일강수량(mm)          132066 non-null  float64
 8   최대 풍속(m/s)        348424 non-null  float64
 9   평균 풍속(m/s)        348338 non-null  float64
 10  최다풍향(16방위)        347878 non-null  float64
 11  평균 이슬점온도(°C)      348089 non-null  float64
 12  최소 상대습도(%)        348587 non-null  float64
 13  평균 상대습도(%)        348121 non-null  float64
 14  평균 증기압(hPa)       348083 non-null  float64
 15  평균 현지기압(hPa)      348352 non-null  float64
 16  최고 해면기압(hPa)      348626 non-null  float64
 17  최저 해면기압(hPa)      348573 non-null  float64
 18  평균 해면기압(hPa)      348291 non-null  float64
 19  합계 일사량(MJ/m2)     174907 non-null  float64
 20  일 최심적설(cm)        3463 non-null    float64
 21  평균 전운량(1/10)      277579 non-null  float64
 22  평균 중하층운량(1/10)    271755 non-null  float64
 23  평균 지면온도(°C)       348349 non-null  float64
 24  평균 5cm 지중온도(°C)   101768 non-null  float64
 25  평균 10cm 지중온도(°C)  101849 non-null  float64
 26  평균 20cm 지중온도(°C)  101872 non-null  float64
 27  평균 30cm 지중온도(°C)  101900 non-null  float64
 28  합계 대형증발량(mm)      167867 non-null  float64
 29  합계 소형증발량(mm)      169427 non-null  float64
dtypes: float64(27), int64(1), str(2)
memory usage: 79.9 MB

,지점,평균기온(°C),최저기온(°C),최고기온(°C),강수 계속시간(hr),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최다풍향(16방위),평균 이슬점온도(°C),...,일 최심적설(cm),평균 전운량(1/10),평균 중하층운량(1/10),평균 지면온도(°C),평균 5cm 지중온도(°C),평균 10cm 지중온도(°C),평균 20cm 지중온도(°C),평균 30cm 지중온도(°C),합계 대형증발량(mm),합계 소형증발량(mm)
count,348870.000000,348373.000000,348716.000000,348722.000000,33584.000000,132066.000000,348424.000000,348338.000000,347878.000000,348089.000000,...,3463.000000,277579.000000,271755.000000,348349.000000,101768.000000,101849.000000,101872.000000,101900.000000,167867.000000,169427.000000
mean,197.456563,13.593346,8.896826,19.010346,5.893667,9.787093,4.693299,1.945511,200.548526,7.368951,...,6.224170,5.145310,2.966391,15.757738,15.640554,15.637694,15.766374,15.805077,2.679325,3.813351
std,64.314290,9.750008,10.389009,9.707497,6.276349,21.102597,2.193126,1.364587,104.164918,11.497721,...,11.971807,2.987424,5.989881,10.905510,9.797245,9.563785,9.207069,8.860353,1.506951,2.150281
min,90.000000,-19.700000,-25.200000,-15.200000,0.000000,0.000000,0.000000,0.000000,20.000000,-30.300000,...,0.000000,0.000000,-999.000000,-14.900000,-8.300000,-7.000000,-5.200000,-5.000000,0.000000,0.000000
25%,136.000000,5.500000,0.300000,11.100000,1.330000,0.100000,3.200000,1.100000,110.000000,-1.700000,...,0.800000,2.600000,0.800000,5.900000,6.800000,7.000000,7.400000,7.800000,1.500000,2.100000
50%,202.000000,14.400000,9.100000,20.200000,4.000000,1.600000,4.300000,1.600000,230.000000,7.800000,...,2.500000,5.300000,2.500000,16.300000,16.200000,16.200000,16.300000,16.300000,2.400000,3.400000
75%,258.000000,21.900000,18.100000,27.000000,8.920000,9.800000,5.600000,2.400000,290.000000,17.500000,...,6.100000,7.700000,4.800000,25.000000,24.300000,24.200000,24.000000,23.800000,3.700000,5.300000
max,296.000000,34.100000,30.600000,41.000000,493.000000,438.900000,49.000000,22.300000,360.000000,79.700000,...,162.800000,10.000000,10.000000,43.300000,38.500000,37.100000,35.700000,34.800000,12.800000,18.200000

In [12]:
weather_df.columns

Index(['지점', '지점명', '일시', '평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '강수 계속시간(hr)',
       '일강수량(mm)', '최대 풍속(m/s)', '평균 풍속(m/s)', '최다풍향(16방위)', '평균 이슬점온도(°C)',
       '최소 상대습도(%)', '평균 상대습도(%)', '평균 증기압(hPa)', '평균 현지기압(hPa)',
       '최고 해면기압(hPa)', '최저 해면기압(hPa)', '평균 해면기압(hPa)', '합계 일사량(MJ/m2)',
       '일 최심적설(cm)', '평균 전운량(1/10)', '평균 중하층운량(1/10)', '평균 지면온도(°C)',
       '평균 5cm 지중온도(°C)', '평균 10cm 지중온도(°C)', '평균 20cm 지중온도(°C)',
       '평균 30cm 지중온도(°C)', '합계 대형증발량(mm)', '합계 소형증발량(mm)'],
      dtype='str')

##### 결측치 채우기

In [13]:
drop_cols = [
    '강수 계속시간(hr)',
    '합계 일사량(MJ/m2)',
    '평균 지면온도(°C)',
    '평균 5cm 지중온도(°C)',
    '평균 10cm 지중온도(°C)',
    '평균 20cm 지중온도(°C)',
    '평균 30cm 지중온도(°C)',
    '합계 대형증발량(mm)',
    '합계 소형증발량(mm)',
    '평균 이슬점온도(°C)',
    '평균 전운량(1/10)',
    '평균 중하층운량(1/10)',
    '평균 증기압(hPa)',
    '평균 현지기압(hPa)',
    '최고 해면기압(hPa)',
    '최저 해면기압(hPa)',
    '평균 해면기압(hPa)',
    '최다풍향(16방위)'
]

# 컬럼 제거
weather_df.drop(columns=drop_cols, inplace=True)

In [14]:
print("날씨데이터 결측치 정확한 개수 확인")
print(weather_df.isnull().sum())

print()

날씨데이터 결측치 정확한 개수 확인
지점                 0
지점명                0
일시                 0
평균기온(°C)         497
최저기온(°C)         154
최고기온(°C)         148
일강수량(mm)      216804
최대 풍속(m/s)       446
평균 풍속(m/s)       532
최소 상대습도(%)       283
평균 상대습도(%)       749
일 최심적설(cm)    345407
dtype: int64

In [15]:
# '일시' 컬럼을 datetime 타입으로 변환
weather_df['일시'] = pd.to_datetime(weather_df['일시'])

# 변환 후 데이터 타입 확인
print(weather_df['일시'].dtype)

# 연, 월, 일 컬럼 생성 (월/일 기준으로 그룹바이)
weather_df['월'] = weather_df['일시'].dt.month
weather_df['일'] = weather_df['일시'].dt.day

datetime64[us]

In [16]:
# 일강수량, 일 최심적설 0 채우기
weather_df['일 최심적설(cm)'] = weather_df['일 최심적설(cm)'].fillna(0)
weather_df['일강수량(mm)'] = weather_df['일강수량(mm)'].fillna(0)

# 습도 -> 지역별 선형보간(습도 결측치 전후일 두날의 평균으로 채움)
weather_df.sort_values(['지점', '일시'], inplace=True)
weather_df['평균 상대습도(%)'] = weather_df.groupby('지점')['평균 상대습도(%)'].transform(lambda x: x.interpolate(method='linear'))
weather_df['최소 상대습도(%)'] = weather_df.groupby('지점')['최소 상대습도(%)'].transform(lambda x: x.interpolate(method='linear'))

# 월/일 컬럼 생성 (이미 만들어졌는지 확인)
weather_df['월'] = weather_df['일시'].dt.month
weather_df['일'] = weather_df['일시'].dt.day

# 나머지 주요 기온/풍속: 지역별 + 월/일 그룹 평균으로 결측치 채우기
cols_group_fill = ['평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '최대 풍속(m/s)', '평균 풍속(m/s)']

for col in cols_group_fill:
    weather_df[col] = weather_df.groupby(['지점', '월', '일'])[col].transform(lambda x: x.fillna(x.mean()))

# 처리 완료 확인
weather_df.isnull().sum()

지점            0
지점명           0
일시            0
평균기온(°C)      0
최저기온(°C)      0
최고기온(°C)      0
일강수량(mm)      0
최대 풍속(m/s)    0
평균 풍속(m/s)    0
최소 상대습도(%)    0
평균 상대습도(%)    1
일 최심적설(cm)    0
월             0
일             0
dtype: int64

In [19]:
# 나음 결측치 1개 처리
weather_df['평균 상대습도(%)'] = weather_df['평균 상대습도(%)'].ffill().bfill()

# 결측치 처리한 데이터 파일 중간 저장
weather_df.to_csv('./data/weather_missingval_fill.csv', encoding='utf-8-sig')

##### 2015 앞에거 5일치 추가하기

In [41]:
# 위에서 채운 결측치 파일 가져오기
weather_df = pd.read_csv('./data/weather_missingval_fill.csv', encoding='utf-8')

# '일시' 컬럼을 datetime 타입으로 변환
weather_df['일시'] = pd.to_datetime(weather_df['일시'])

fivedays_df = pd.read_csv('./data/weather_20151227_20151231.csv', encoding='cp949')

fivedays_df['일시'] = pd.to_datetime(fivedays_df['일시'])

# weather_df의 컬럼들 중 fivedays에도 존재하는 컬럼명만 리스트로 만들기
common_cols = [col for col in weather_df.columns if col in fivedays_df]

# 공통된 컬럼만 추출
fivedays_df = fivedays_df[common_cols]

full_df = pd.concat([fivedays_df, weather_df], axis=0)

# 날짜순, 지점별로 다시 정렬 (이걸 해야 shift가 정확히 작동합니다)
full_df = full_df.sort_values(['지점명', '일시']).reset_index(drop=True)

##### '실효습도' column 생성

In [42]:
# '실효습도' column 생성
r = 0.7
weighted_sum = 0

for i in range(6): # 0부터 5까지
    h_i = full_df.groupby('지점명')['평균 상대습도(%)'].shift(i)
    weighted_sum += (r**i) * h_i

full_df['실효습도'] = (1-r) * weighted_sum

# '일시' 컬럼의 연도가 2016년 이상인 것만 남기기
weather_df = full_df[full_df['일시'].dt.year >= 2016].copy()

In [43]:
# 실효습도 null값이 2016(데이터의 시작)이 아닌 지점 확인
print(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year != 2016)].shape)
display(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year != 2016)])
# -> 서청주 2023, 세종 2019, 북부산 2023 확인 5개씩 15개 확인

(15, 17)

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),Unnamed: 0.1,Unnamed: 0,월,일,실효습도
128022,296,북부산,2023-01-11,4.700000,-2.7,14.6,0.0,3.3,0.700000,16.0,65.5,0.0,128022.0,347784.0,1.0,11.0,NaN
128023,296,북부산,2023-01-12,7.800000,-2.0,16.6,0.0,3.7,1.100000,27.0,75.0,0.0,128023.0,347785.0,1.0,12.0,NaN
128024,296,북부산,2023-01-13,14.900000,10.9,17.6,74.5,5.5,1.700000,86.0,93.3,0.0,128024.0,347786.0,1.0,13.0,NaN
128025,296,북부산,2023-01-14,10.600000,8.4,13.0,1.0,5.7,3.600000,75.0,82.9,0.0,128025.0,347787.0,1.0,14.0,NaN
128026,296,북부산,2023-01-15,6.400000,1.9,8.4,0.5,4.3,1.800000,63.0,79.9,0.0,128026.0,347788.0,1.0,15.0,NaN
154433,181,서청주,2023-05-01,13.600000,6.9,21.0,0.0,5.6,2.200000,20.0,55.3,0.0,154433.0,150806.0,5.0,1.0,NaN
154434,181,서청주,2023-05-02,16.000000,3.7,26.3,0.0,4.0,1.200000,15.0,46.8,0.0,154434.0,150807.0,5.0,2.0,NaN
154435,181,서청주,2023-05-03,18.800000,10.0,26.5,0.0,4.4,1.700000,18.0,50.9,0.0,154435.0,150808.0,5.0,3.0,NaN
154436,181,서청주,2023-05-04,20.100000,13.2,27.3,0.8,5.4,2.400000,43.0,66.4,0.0,154436.0,150809.0,5.0,4.0,NaN
154437,181,서청주,2023-05-05,19.600000,16.9,21.5,49.1,3.5,1.200000,83.0,93.0,0.0,154437.0,150810.0,5.0,5.0,NaN
159067,239,세종,2019-05-31,20.466667,13.7,24.1,0.2,3.3,1.333333,39.0,51.3,0.0,159067.0,217532.0,5.0,31.0,NaN
159068,239,세종,2019-06-01,17.400000,10.8,23.5,0.0,2.7,0.900000,44.0,69.9,0.0,159068.0,217533.0,6.0,1.0,NaN
159069,239,세종,2019-06-02,21.000000,13.5,28.0,0.0,3.2,1.100000,26.0,53.5,0.0,159069.0,217534.0,6.0,2.0,NaN
159070,239,세종,2019-06-03,22.200000,13.9,29.5,0.0,4.1,0.900000,25.0,47.0,0.0,159070.0,217535.0,6.0,3.0,NaN
159071,239,세종,2019-06-04,23.100000,16.3,30.9,0.0,3.1,1.200000,25.0,53.9,0.0,159071.0,217536.0,6.0,4.0,NaN

In [44]:
# 실효습도 null값이 2016인 지점 확인
print(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year == 2016)].shape)
display(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year == 2016)])

(11, 17)

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),Unnamed: 0.1,Unnamed: 0,월,일,실효습도
80474,106,동해,2016-01-01,6.4,0.5,11.6,0.0,5.3,1.7,18.0,35.9,0.0,80474.0,36254.0,1.0,1.0,NaN
80475,106,동해,2016-01-02,9.8,5.3,14.1,0.0,4.8,1.6,24.0,46.3,0.0,80475.0,36255.0,1.0,2.0,NaN
80476,106,동해,2016-01-03,9.9,5.3,14.1,0.0,3.4,1.3,41.0,64.0,0.0,80476.0,36256.0,1.0,3.0,NaN
132766,93,북춘천,2016-10-01,18.6,14.7,25.3,0.0,2.1,0.6,48.0,79.3,0.0,132766.0,3653.0,10.0,1.0,NaN
132767,93,북춘천,2016-10-02,17.0,15.6,19.4,31.5,4.4,0.7,78.0,89.0,0.0,132767.0,3654.0,10.0,2.0,NaN
132768,93,북춘천,2016-10-03,20.5,15.0,29.0,39.0,3.7,0.9,49.0,81.1,0.0,132768.0,3655.0,10.0,3.0,NaN
132769,93,북춘천,2016-10-04,18.3,11.4,26.3,0.0,4.5,1.5,42.0,72.4,0.0,132769.0,3656.0,10.0,4.0,NaN
132770,93,북춘천,2016-10-05,18.0,14.2,25.6,0.0,5.0,1.3,47.0,79.4,0.0,132770.0,3657.0,10.0,5.0,NaN
161479,90,속초,2016-01-01,3.6,-2.3,7.6,0.0,6.3,2.3,30.0,44.9,0.0,161479.0,0.0,1.0,1.0,NaN
161480,90,속초,2016-01-02,8.4,5.0,11.5,0.0,8.0,3.1,38.0,50.4,0.0,161480.0,1.0,1.0,2.0,NaN
161481,90,속초,2016-01-03,6.7,2.4,9.8,0.0,5.3,1.9,53.0,80.0,0.0,161481.0,2.0,1.0,3.0,NaN

In [45]:
# 실효습도가 NaN인 행(신설 지점 초반 데이터)만 삭제
# weather_df = weather_df.dropna(subset=['실효습도'])

weather_df.isna().sum()

지점               0
지점명              0
일시               0
평균기온(°C)         0
최저기온(°C)         0
최고기온(°C)         0
일강수량(mm)         0
최대 풍속(m/s)       0
평균 풍속(m/s)       0
최소 상대습도(%)       0
평균 상대습도(%)       0
일 최심적설(cm)       0
Unnamed: 0.1     0
Unnamed: 0       0
월                0
일                0
실효습도            26
dtype: int64

##### 전처리 오래 걸리므로 파일 저장

In [46]:
# 한글 데이터가 포함되어 있으므로 encoding='utf-8-sig'를 권장합니다 (엑셀에서도 잘 열림)
# index=False를 안 하면 나중에 불러올 때 'Unnamed: 0' 컬럼이 생기니 꼭 넣어주세요.
weather_df.to_csv('./data/weather_preprocessed.csv', index=False, encoding='utf-8-sig')

print("전처리 완료 데이터 저장 성공!")
# 저장했던 파일 불러오기
weather_df = pd.read_csv('./data/weather_preprocessed.csv', encoding='utf-8-sig')

# 불러온 후 '일시' 컬럼이 다시 object(str)로 변했을 수 있으니 datetime으로 다시 바꿔주면 완벽합니다.
weather_df['일시'] = pd.to_datetime(weather_df['일시'])

weather_df.isna().sum()
weather_df

전처리 완료 데이터 저장 성공!

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),Unnamed: 0.1,Unnamed: 0,월,일,실효습도
0,105,강릉,2016-01-01,5.1,2.1,8.9,0.0,9.6,4.8,20.0,33.0,0.0,5.0,32601.0,1.0,1.0,32.568148
1,105,강릉,2016-01-02,9.1,5.5,11.2,0.0,9.5,4.9,35.0,43.8,0.0,6.0,32602.0,1.0,2.0,34.257676
2,105,강릉,2016-01-03,9.0,5.3,13.8,0.0,5.7,2.6,31.0,55.8,0.0,7.0,32603.0,1.0,3.0,40.240365
3,105,강릉,2016-01-04,7.4,3.3,12.0,0.0,6.9,3.4,13.0,33.8,0.0,8.0,32604.0,1.0,4.0,37.708246
4,105,강릉,2016-01-05,3.0,0.4,7.7,0.0,5.7,3.7,10.0,16.3,0.0,9.0,32605.0,1.0,5.0,29.817512
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348865,169,흑산도,2025-12-27,3.2,1.2,6.0,0.0,6.5,3.5,57.0,72.3,0.0,349335.0,134877.0,12.0,27.0,63.150884
348866,169,흑산도,2025-12-28,7.8,3.4,14.2,0.4,7.1,4.7,47.0,72.1,0.0,349336.0,134878.0,12.0,28.0,63.619111
348867,169,흑산도,2025-12-29,10.0,6.3,14.5,0.0,9.7,5.6,56.0,71.8,0.0,349337.0,134879.0,12.0,29.0,62.949797
348868,169,흑산도,2025-12-30,4.8,3.5,6.5,0.0,11.9,9.2,45.0,56.5,0.0,349338.0,134880.0,12.0,30.0,58.328931
348869,169,흑산도,2025-12-31,2.3,0.3,5.2,0.0,14.7,11.4,56.0,66.9,0.0,349339.0,134881.0,12.0,31.0,58.666097