# 날씨 데이터

In [47]:
import pandas as pd

### 날씨 데이터 확인

In [48]:
weather_df = pd.read_csv('./data/weather_2016_2025.csv', encoding='cp949')

In [49]:
weather_df.info()
weather_df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 348870 entries, 0 to 348869
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   지점                348870 non-null  int64
 1   지점명               348870 non-null  str
 2   일시                348870 non-null  str
 3   평균기온(°C)          348373 non-null  float64
 4   최저기온(°C)          348716 non-null  float64
 5   최고기온(°C)          348722 non-null  float64
 6   강수 계속시간(hr)       33584 non-null   float64
 7   일강수량(mm)          132066 non-null  float64
 8   최대 풍속(m/s)        348424 non-null  float64
 9   평균 풍속(m/s)        348338 non-null  float64
 10  최다풍향(16방위)        347878 non-null  float64
 11  평균 이슬점온도(°C)      348089 non-null  float64
 12  최소 상대습도(%)        348587 non-null  float64
 13  평균 상대습도(%)        348121 non-null  float64
 14  평균 증기압(hPa)       348083 non-null  float64
 15  평균 현지기압(hPa)      348352 non-null  float64
 16  최고 해면기압(hPa)      348626 non-null  float64
 17  최저 해면기압(hPa)      348573 non-null  float64
 18  평균 해면기압(hPa)      348291 non-null  float64
 19  합계 일사량(MJ/m2)     174907 non-null  float64
 20  일 최심적설(cm)        3463 non-null    float64
 21  평균 전운량(1/10)      277579 non-null  float64
 22  평균 중하층운량(1/10)    271755 non-null  float64
 23  평균 지면온도(°C)       348349 non-null  float64
 24  평균 5cm 지중온도(°C)   101768 non-null  float64
 25  평균 10cm 지중온도(°C)  101849 non-null  float64
 26  평균 20cm 지중온도(°C)  101872 non-null  float64
 27  평균 30cm 지중온도(°C)  101900 non-null  float64
 28  합계 대형증발량(mm)      167867 non-null  float64
 29  합계 소형증발량(mm)      169427 non-null  float64
dtypes: float64(27), int64(1), str(2)
memory usage: 79.9 MB

,지점,평균기온(°C),최저기온(°C),최고기온(°C),강수 계속시간(hr),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최다풍향(16방위),평균 이슬점온도(°C),...,일 최심적설(cm),평균 전운량(1/10),평균 중하층운량(1/10),평균 지면온도(°C),평균 5cm 지중온도(°C),평균 10cm 지중온도(°C),평균 20cm 지중온도(°C),평균 30cm 지중온도(°C),합계 대형증발량(mm),합계 소형증발량(mm)
count,348870.000000,348373.000000,348716.000000,348722.000000,33584.000000,132066.000000,348424.000000,348338.000000,347878.000000,348089.000000,...,3463.000000,277579.000000,271755.000000,348349.000000,101768.000000,101849.000000,101872.000000,101900.000000,167867.000000,169427.000000
mean,197.456563,13.593346,8.896826,19.010346,5.893667,9.787093,4.693299,1.945511,200.548526,7.368951,...,6.224170,5.145310,2.966391,15.757738,15.640554,15.637694,15.766374,15.805077,2.679325,3.813351
std,64.314290,9.750008,10.389009,9.707497,6.276349,21.102597,2.193126,1.364587,104.164918,11.497721,...,11.971807,2.987424,5.989881,10.905510,9.797245,9.563785,9.207069,8.860353,1.506951,2.150281
min,90.000000,-19.700000,-25.200000,-15.200000,0.000000,0.000000,0.000000,0.000000,20.000000,-30.300000,...,0.000000,0.000000,-999.000000,-14.900000,-8.300000,-7.000000,-5.200000,-5.000000,0.000000,0.000000
25%,136.000000,5.500000,0.300000,11.100000,1.330000,0.100000,3.200000,1.100000,110.000000,-1.700000,...,0.800000,2.600000,0.800000,5.900000,6.800000,7.000000,7.400000,7.800000,1.500000,2.100000
50%,202.000000,14.400000,9.100000,20.200000,4.000000,1.600000,4.300000,1.600000,230.000000,7.800000,...,2.500000,5.300000,2.500000,16.300000,16.200000,16.200000,16.300000,16.300000,2.400000,3.400000
75%,258.000000,21.900000,18.100000,27.000000,8.920000,9.800000,5.600000,2.400000,290.000000,17.500000,...,6.100000,7.700000,4.800000,25.000000,24.300000,24.200000,24.000000,23.800000,3.700000,5.300000
max,296.000000,34.100000,30.600000,41.000000,493.000000,438.900000,49.000000,22.300000,360.000000,79.700000,...,162.800000,10.000000,10.000000,43.300000,38.500000,37.100000,35.700000,34.800000,12.800000,18.200000

In [50]:
weather_df.columns

Index(['지점', '지점명', '일시', '평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '강수 계속시간(hr)',
       '일강수량(mm)', '최대 풍속(m/s)', '평균 풍속(m/s)', '최다풍향(16방위)', '평균 이슬점온도(°C)',
       '최소 상대습도(%)', '평균 상대습도(%)', '평균 증기압(hPa)', '평균 현지기압(hPa)',
       '최고 해면기압(hPa)', '최저 해면기압(hPa)', '평균 해면기압(hPa)', '합계 일사량(MJ/m2)',
       '일 최심적설(cm)', '평균 전운량(1/10)', '평균 중하층운량(1/10)', '평균 지면온도(°C)',
       '평균 5cm 지중온도(°C)', '평균 10cm 지중온도(°C)', '평균 20cm 지중온도(°C)',
       '평균 30cm 지중온도(°C)', '합계 대형증발량(mm)', '합계 소형증발량(mm)'],
      dtype='str')

##### 결측치 채우기

In [51]:
drop_cols = [
    '강수 계속시간(hr)',
    '합계 일사량(MJ/m2)',
    '평균 지면온도(°C)',
    '평균 5cm 지중온도(°C)',
    '평균 10cm 지중온도(°C)',
    '평균 20cm 지중온도(°C)',
    '평균 30cm 지중온도(°C)',
    '합계 대형증발량(mm)',
    '합계 소형증발량(mm)',
    '평균 이슬점온도(°C)',
    '평균 전운량(1/10)',
    '평균 중하층운량(1/10)',
    '평균 증기압(hPa)',
    '평균 현지기압(hPa)',
    '최고 해면기압(hPa)',
    '최저 해면기압(hPa)',
    '평균 해면기압(hPa)',
    '최다풍향(16방위)'
]

# 컬럼 제거
weather_df.drop(columns=drop_cols, inplace=True)

In [52]:
print("날씨데이터 결측치 정확한 개수 확인")
print(weather_df.isnull().sum())

print()

날씨데이터 결측치 정확한 개수 확인
지점                 0
지점명                0
일시                 0
평균기온(°C)         497
최저기온(°C)         154
최고기온(°C)         148
일강수량(mm)      216804
최대 풍속(m/s)       446
평균 풍속(m/s)       532
최소 상대습도(%)       283
평균 상대습도(%)       749
일 최심적설(cm)    345407
dtype: int64

In [53]:
# '일시' 컬럼을 datetime 타입으로 변환
weather_df['일시'] = pd.to_datetime(weather_df['일시'])

# 변환 후 데이터 타입 확인
print(weather_df['일시'].dtype)

# 연, 월, 일 컬럼 생성 (월/일 기준으로 그룹바이)
weather_df['월'] = weather_df['일시'].dt.month
weather_df['일'] = weather_df['일시'].dt.day

datetime64[us]

In [54]:
# 일강수량, 일 최심적설 0 채우기
weather_df['일 최심적설(cm)'] = weather_df['일 최심적설(cm)'].fillna(0)
weather_df['일강수량(mm)'] = weather_df['일강수량(mm)'].fillna(0)

# 습도 -> 지역별 선형보간(습도 결측치 전후일 두날의 평균으로 채움)
weather_df.sort_values(['지점', '일시'], inplace=True)
weather_df['평균 상대습도(%)'] = weather_df.groupby('지점')['평균 상대습도(%)'].transform(lambda x: x.interpolate(method='linear'))
weather_df['최소 상대습도(%)'] = weather_df.groupby('지점')['최소 상대습도(%)'].transform(lambda x: x.interpolate(method='linear'))

# 월/일 컬럼 생성 (이미 만들어졌는지 확인)
weather_df['월'] = weather_df['일시'].dt.month
weather_df['일'] = weather_df['일시'].dt.day

# 나머지 주요 기온/풍속: 지역별 + 월/일 그룹 평균으로 결측치 채우기
cols_group_fill = ['평균기온(°C)', '최저기온(°C)', '최고기온(°C)', '최대 풍속(m/s)', '평균 풍속(m/s)']

for col in cols_group_fill:
    weather_df[col] = weather_df.groupby(['지점', '월', '일'])[col].transform(lambda x: x.fillna(x.mean()))

# 처리 완료 확인
weather_df.isnull().sum()

지점            0
지점명           0
일시            0
평균기온(°C)      0
최저기온(°C)      0
최고기온(°C)      0
일강수량(mm)      0
최대 풍속(m/s)    0
평균 풍속(m/s)    0
최소 상대습도(%)    0
평균 상대습도(%)    1
일 최심적설(cm)    0
월             0
일             0
dtype: int64

In [56]:
# 나음 결측치 1개 처리
weather_df['평균 상대습도(%)'] = weather_df['평균 상대습도(%)'].ffill().bfill()

##### 2015 앞에거 5일치 추가하기

In [93]:
fivedays_df = pd.read_csv('./data/weather_20151227_20151231.csv', encoding='cp949')

fivedays_df['일시'] = pd.to_datetime(fivedays_df['일시'])

# weather_df의 컬럼들 중 fivedays에도 존재하는 컬럼명만 리스트로 만들기
common_cols = [col for col in weather_df.columns if col in fivedays_df]

# 공통된 컬럼만 추출
fivedays_df = fivedays_df[common_cols]

full_df = pd.concat([fivedays_df, weather_df], axis=0)

# 날짜순, 지점별로 다시 정렬 (이걸 해야 shift가 정확히 작동합니다)
full_df = full_df.sort_values(['지점명', '일시']).reset_index(drop=True)

##### '실효습도' column 생성

In [94]:
# '실효습도' column 생성
r = 0.7
weighted_sum = 0

for i in range(6): # 0부터 5까지
    h_i = full_df.groupby('지점명')['평균 상대습도(%)'].shift(i)
    weighted_sum += (r**i) * h_i

full_df['실효습도'] = (1-r) * weighted_sum

# '일시' 컬럼의 연도가 2016년 이상인 것만 남기기
weather_df = full_df[full_df['일시'].dt.year >= 2016].copy()

In [ ]:
# 실효습도 null값이 2016(데이터의 시작)이 아닌 지점 확인
print(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year != 2016)].shape)
display(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year != 2016)])
# -> 서청주 2023, 세종 2019, 북부산 2023 확인 5개씩 15개 확인

# 실효습도가 NaN인 행(신설 지점 초반 데이터)만 삭제
weather_df = weather_df.dropna(subset=['실효습도'])

weather_df.isna().sum()

(18, 15)

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),월,일,실효습도
132578,93,북춘천,2019-09-11,3.7,1.2,7.2,1.5,3.6,1.2,70.0,89.3,0.0,1.0,14.0,NaN
132579,93,북춘천,2019-09-12,0.0,-1.2,1.6,8.9,2.6,0.5,90.0,97.0,5.0,1.0,15.0,NaN
132580,93,북춘천,2019-09-13,-4.6,-9.6,-1.2,0.0,2.9,1.3,63.0,82.1,3.6,1.0,16.0,NaN
132581,93,북춘천,2019-09-14,-6.0,-9.9,-3.5,0.1,1.6,0.6,63.0,85.6,3.4,1.0,17.0,NaN
132582,93,북춘천,2019-09-15,-5.1,-9.9,0.6,0.0,2.8,0.6,44.0,84.4,4.0,1.0,18.0,NaN
154215,181,서청주,2022-08-30,14.1,12.0,20.3,32.5,7.5,3.9,82.0,90.4,0.0,5.0,6.0,NaN
154216,181,서청주,2022-08-31,12.1,7.4,15.0,0.2,6.4,2.5,57.0,75.8,0.0,5.0,7.0,NaN
154217,181,서청주,2022-09-01,13.0,4.5,22.4,0.0,5.3,1.5,25.0,64.8,0.0,5.0,8.0,NaN
154218,181,서청주,2022-09-02,15.5,5.8,24.9,0.0,4.8,1.5,21.0,63.1,0.0,5.0,9.0,NaN
154219,181,서청주,2022-09-03,17.3,8.5,25.7,0.0,4.3,1.6,24.0,55.8,0.0,5.0,10.0,NaN
158839,239,세종,2025-04-27,-0.5,-4.0,4.7,0.0,2.3,0.9,32.0,54.3,0.0,1.0,17.0,NaN
158840,239,세종,2025-04-28,0.2,-5.5,7.1,0.0,2.3,0.8,20.0,54.0,0.0,1.0,18.0,NaN
158841,239,세종,2025-04-29,1.5,-3.6,7.8,0.0,3.8,1.2,40.0,62.4,0.0,1.0,19.0,NaN
158842,239,세종,2025-04-30,2.2,-1.2,7.2,0.0,4.9,1.8,28.0,57.9,0.0,1.0,20.0,NaN
158843,239,세종,2025-05-01,-0.3,-5.6,5.3,0.0,3.3,0.9,17.0,41.9,0.0,1.0,21.0,NaN
161241,90,속초,2021-11-23,2.8,-0.7,6.3,12.0,3.8,2.3,30.0,57.8,0.0,1.0,17.0,NaN
161242,90,속초,2021-11-24,2.4,0.1,6.9,15.3,2.9,1.7,32.0,78.9,0.0,1.0,18.0,NaN
161243,90,속초,2021-11-25,3.3,1.6,5.7,0.0,6.4,2.7,28.0,40.5,0.0,1.0,19.0,NaN

지점            0
지점명           0
일시            0
평균기온(°C)      0
최저기온(°C)      0
최고기온(°C)      0
일강수량(mm)      0
최대 풍속(m/s)    0
평균 풍속(m/s)    0
최소 상대습도(%)    0
평균 상대습도(%)    0
일 최심적설(cm)    0
월             0
일             0
실효습도          0
dtype: int64

##### 전처리 오래 걸리므로 파일 저장

In [101]:
# 한글 데이터가 포함되어 있으므로 encoding='utf-8-sig'를 권장합니다 (엑셀에서도 잘 열림)
# index=False를 안 하면 나중에 불러올 때 'Unnamed: 0' 컬럼이 생기니 꼭 넣어주세요.
weather_df.to_csv('./data/weather_preprocessed.csv', index=False, encoding='utf-8-sig')

print("전처리 완료 데이터 저장 성공!")
# 저장했던 파일 불러오기
weather_df = pd.read_csv('./data/weather_preprocessed.csv', encoding='utf-8-sig')

# 불러온 후 '일시' 컬럼이 다시 object(str)로 변했을 수 있으니 datetime으로 다시 바꿔주면 완벽합니다.
weather_df['일시'] = pd.to_datetime(weather_df['일시'])

weather_df.isna().sum()

전처리 완료 데이터 저장 성공!

지점            0
지점명           0
일시            0
평균기온(°C)      0
최저기온(°C)      0
최고기온(°C)      0
일강수량(mm)      0
최대 풍속(m/s)    0
평균 풍속(m/s)    0
최소 상대습도(%)    0
평균 상대습도(%)    0
일 최심적설(cm)    0
월             0
일             0
실효습도          0
dtype: int64

##### 재훈&혜린 전처리 데이터 합치기

In [109]:
preprocessed_df = pd.read_csv('./머신러닝용_ver_0.1.csv', encoding='cp949')

FileNotFoundError: [Errno 2] No such file or directory: './머신러닝용_ver_0.1.csv'