In [20]:
import pandas as pd

df = pd.read_csv('./data1/머신러닝용_final.csv')
df

,Unnamed: 0,시도,일시,fire,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),일 최심적설(cm),실효습도
0,0,경북,2016-01-03,1,4.376923,16.3,0.0,72.415385,6.5,1.184615,-6.6,0.0,59.201499
1,1,경북,2016-01-04,0,5.192308,12.9,0.0,50.807692,8.3,2.715385,-6.2,0.0,55.198808
2,2,경북,2016-01-05,0,0.423077,7.0,0.0,33.076923,8.1,2.646154,-7.0,0.0,46.443746
3,3,경북,2016-01-06,1,0.084615,7.0,0.0,46.515385,9.6,2.976923,-9.8,0.0,43.977776
4,4,경북,2016-01-07,0,-0.030769,6.4,0.0,44.192308,8.1,3.092308,-9.2,0.0,41.731961
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62013,63262,제주,2025-12-27,0,4.200000,9.4,0.0,59.325000,6.1,2.625000,-2.8,0.0,54.115659
62014,63263,제주,2025-12-28,0,8.950000,13.7,0.0,53.875000,12.7,2.800000,1.0,0.0,51.877249
62015,63264,제주,2025-12-29,0,12.325000,17.3,0.0,60.600000,11.5,4.400000,5.0,0.0,52.197272
62016,63265,제주,2025-12-30,0,8.325000,15.8,0.0,51.725000,10.3,3.700000,3.6,0.0,49.414664
62017,63266,제주,2025-12-31,0,5.075000,12.4,0.0,55.400000,15.7,5.250000,0.8,0.0,49.192290

In [21]:
# 년도 컬럼 신설
df['년도'] = df['일시'].str[:4].astype(int)
df

,Unnamed: 0,시도,일시,fire,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),일 최심적설(cm),실효습도,년도
0,0,경북,2016-01-03,1,4.376923,16.3,0.0,72.415385,6.5,1.184615,-6.6,0.0,59.201499,2016
1,1,경북,2016-01-04,0,5.192308,12.9,0.0,50.807692,8.3,2.715385,-6.2,0.0,55.198808,2016
2,2,경북,2016-01-05,0,0.423077,7.0,0.0,33.076923,8.1,2.646154,-7.0,0.0,46.443746,2016
3,3,경북,2016-01-06,1,0.084615,7.0,0.0,46.515385,9.6,2.976923,-9.8,0.0,43.977776,2016
4,4,경북,2016-01-07,0,-0.030769,6.4,0.0,44.192308,8.1,3.092308,-9.2,0.0,41.731961,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62013,63262,제주,2025-12-27,0,4.200000,9.4,0.0,59.325000,6.1,2.625000,-2.8,0.0,54.115659,2025
62014,63263,제주,2025-12-28,0,8.950000,13.7,0.0,53.875000,12.7,2.800000,1.0,0.0,51.877249,2025
62015,63264,제주,2025-12-29,0,12.325000,17.3,0.0,60.600000,11.5,4.400000,5.0,0.0,52.197272,2025
62016,63265,제주,2025-12-30,0,8.325000,15.8,0.0,51.725000,10.3,3.700000,3.6,0.0,49.414664,2025
62017,63266,제주,2025-12-31,0,5.075000,12.4,0.0,55.400000,15.7,5.250000,0.8,0.0,49.192290,2025

In [22]:
df1 = pd.read_csv('전국_농지비율.csv',encoding='CP949')
df2 = pd.read_csv('전국_도시산림_인접지수.csv',encoding='CP949')

# 농지비율 컬럼 이름 통일
df_nongjy = df1.rename(columns={'발생일시_년':'년도','발생장소_시도':'시도'})

In [23]:
# wui 컬럼 이름 통일
df_wui = df2.rename(columns={'시점':'년도','행정구역별':'시도'})

In [24]:
# 산불-날씨 데이터와 merge
df_merge = df.merge(df_nongjy,on=['년도','시도']).merge(df_wui,on=['년도','시도'])

In [26]:
df_merge.to_csv('최종전처리.csv', encoding='cp949', index=False)

In [ ]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62018 entries, 0 to 62017
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  62018 non-null  int64
 1   시도          62018 non-null  object
 2   일시          62018 non-null  object
 3   fire        62018 non-null  int64
 4   평균기온(°C)    62018 non-null  float64
 5   최고기온(°C)    62018 non-null  float64
 6   일강수량(mm)    62018 non-null  float64
 7   평균 상대습도(%)  62018 non-null  float64
 8   최대 풍속(m/s)  62018 non-null  float64
 9   평균 풍속(m/s)  62018 non-null  float64
 10  최저기온(°C)    62018 non-null  float64
 11  일 최심적설(cm)  62018 non-null  float64
 12  실효습도        62018 non-null  float64
 13  년도          62018 non-null  int64
 14  논_비율        62018 non-null  float64
 15  밭_비율        62018 non-null  float64
 16  도시_산림_인접지수  62018 non-null  float64
dtypes: float64(12), int64(3), object(2)
memory usage: 8.0+ MB