In [2]:
import pandas as pd

mt_fire = pd.read_excel('sanbul.xlsx', header=2)
mt_fire

,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,발생장소_시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계
0,2025,12,31,15:56,수,2025,12,31,20:30,경북,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30
1,2025,12,30,11:03,화,2025,12,30,12:40,전남,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15
2,2025,12,30,05:00,화,2025,12,30,05:47,대구,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02
3,2025,12,29,20:00,월,2025,12,29,22:35,강원,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36
4,2025,12,29,14:14,월,2025,12,29,23:51,강원,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5286,2016,1,8,13:20,금,2016,1,8,14:15,경북,경북,칠곡,동명,금암,쓰,기타(직접입력),쓰레기 소각,0.20
5287,2016,1,6,17:48,수,2016,1,6,21:20,경북,경북,울진,금강송,광회,NaN,주택화재비화,주택내 불씨취급 부주의,0.30
5288,2016,1,6,15:13,수,2016,1,6,16:30,강원,강원,고성,거진,거진,담,기타(직접입력),담뱃불 실화,0.06
5289,2016,1,5,14:31,화,2016,1,5,17:30,경기,경기,성남 수정,NaN,금토,기,무속행위,무속행위,0.10
5290,2016,1,3,14:03,일,2016,1,3,16:20,경북,경북,영양,청기,상청,입,기타(직접입력),입산자 실화추정,0.50

In [3]:
# mt_fire.info()
mt_fire['발생장소_시도'].unique()

array(['경북', '전남', '대구', '강원', '부산', '경남', '경기', '충남', '충북', '인천', '울산',
       '전북', '서울', '광주', '대전', '세종', '제주'], dtype=object)

In [4]:
# mt_fire['locsi'].unique()
mt_fire = mt_fire.rename(columns={'발생장소_시도':'시도'
})
mt_fire['일시'] = pd.to_datetime(mt_fire['발생일시_년'].astype(str)+'-'+mt_fire['발생일시_월'].astype(str)+'-'+mt_fire['발생일시_일'].astype(str)).dt.date

In [5]:
mt_fire.head(5)

,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,일시
0,2025,12,31,15:56,수,2025,12,31,20:30,경북,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30,2025-12-31
1,2025,12,30,11:03,화,2025,12,30,12:40,전남,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15,2025-12-30
2,2025,12,30,05:00,화,2025,12,30,05:47,대구,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02,2025-12-30
3,2025,12,29,20:00,월,2025,12,29,22:35,강원,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36,2025-12-29
4,2025,12,29,14:14,월,2025,12,29,23:51,강원,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10,2025-12-29

In [6]:
# 산불 데이터 발생유무
mt_fire['산불발생'] = 1
mt_fire

,발생일시_년,발생일시_월,발생일시_일,발생일시_시간,발생일시_요일,진화종료시간_년,진화종료시간_월,진화종료시간_일,진화종료시간_시간,발생장소_관서,시도,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,일시,산불발생
0,2025,12,31,15:56,수,2025,12,31,20:30,경북,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30,2025-12-31,1
1,2025,12,30,11:03,화,2025,12,30,12:40,전남,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15,2025-12-30,1
2,2025,12,30,05:00,화,2025,12,30,05:47,대구,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02,2025-12-30,1
3,2025,12,29,20:00,월,2025,12,29,22:35,강원,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36,2025-12-29,1
4,2025,12,29,14:14,월,2025,12,29,23:51,강원,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10,2025-12-29,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5286,2016,1,8,13:20,금,2016,1,8,14:15,경북,경북,칠곡,동명,금암,쓰,기타(직접입력),쓰레기 소각,0.20,2016-01-08,1
5287,2016,1,6,17:48,수,2016,1,6,21:20,경북,경북,울진,금강송,광회,NaN,주택화재비화,주택내 불씨취급 부주의,0.30,2016-01-06,1
5288,2016,1,6,15:13,수,2016,1,6,16:30,강원,강원,고성,거진,거진,담,기타(직접입력),담뱃불 실화,0.06,2016-01-06,1
5289,2016,1,5,14:31,화,2016,1,5,17:30,경기,경기,성남 수정,NaN,금토,기,무속행위,무속행위,0.10,2016-01-05,1
5290,2016,1,3,14:03,일,2016,1,3,16:20,경북,경북,영양,청기,상청,입,기타(직접입력),입산자 실화추정,0.50,2016-01-03,1

In [13]:
# 결측치 채워진 날씨 데이터
weather_df = pd.read_csv('weather_data.csv')
weather_df

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),월,일
0,90,속초,2016-01-01,3.6,-2.3,7.6,0.0,6.3,2.3,30.0,44.9,0.0,1,1
1,90,속초,2016-01-02,8.4,5.0,11.5,0.0,8.0,3.1,38.0,50.4,0.0,1,2
2,90,속초,2016-01-03,6.7,2.4,9.8,0.0,5.3,1.9,53.0,80.0,0.0,1,3
3,90,속초,2016-01-04,5.4,0.8,9.0,0.0,5.9,2.7,13.0,32.6,0.0,1,4
4,90,속초,2016-01-05,0.6,-2.6,4.4,0.0,6.1,2.5,9.0,16.8,0.0,1,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348865,296,북부산,2025-12-27,-0.1,-5.9,7.0,0.0,3.5,1.5,21.0,50.1,0.0,12,27
348866,296,북부산,2025-12-28,2.4,-4.4,11.2,0.0,2.6,0.9,38.0,69.6,0.0,12,28
348867,296,북부산,2025-12-29,5.9,-1.5,14.9,0.0,2.4,0.7,44.0,73.6,0.0,12,29
348868,296,북부산,2025-12-30,3.1,-3.6,10.1,0.0,4.7,1.6,15.0,50.4,0.0,12,30
348869,296,북부산,2025-12-31,0.3,-4.7,5.3,0.0,4.4,2.1,13.0,38.3,0.0,12,31

In [16]:

# '일시' 컬럼을 datetime 타입으로 변환
weather_df['일시'] = pd.to_datetime(weather_df['일시'])

fivedays_df = pd.read_csv('weather_20151227_20151231.csv', encoding='cp949')

fivedays_df['일시'] = pd.to_datetime(fivedays_df['일시'])

# weather_df의 컬럼들 중 fivedays에도 존재하는 컬럼명만 리스트로 만들기
common_cols = [col for col in weather_df.columns if col in fivedays_df]

# 공통된 컬럼만 추출
fivedays_df = fivedays_df[common_cols]

full_df = pd.concat([fivedays_df, weather_df], axis=0)

# 날짜순, 지점별로 다시 정렬 (이걸 해야 shift가 정확히 작동합니다)
full_df = full_df.sort_values(['지점명', '일시']).reset_index(drop=True)


# '실효습도' column 생성
r = 0.7
weighted_sum = 0

for i in range(6): # 0부터 5까지
    h_i = full_df.groupby('지점명')['평균 상대습도(%)'].shift(i)
    weighted_sum += (r**i) * h_i

full_df['실효습도'] = (1-r) * weighted_sum

# '일시' 컬럼의 연도가 2016년 이상인 것만 남기기
weather_df = full_df[full_df['일시'].dt.year >= 2016].copy()

# 실효습도 null값이 2016(데이터의 시작)이 아닌 지점 확인
print(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year != 2016)].shape)
display(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year != 2016)])
# -> 서청주 2023, 세종 2019, 북부산 2023 확인 5개씩 15개 확인

# 실효습도 null값이 2016인 지점 확인
print(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year == 2016)].shape)
display(weather_df[weather_df['실효습도'].isnull() & (weather_df['일시'].dt.year == 2016)])

(15, 15)

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),월,일,실효습도
128022,296,북부산,2023-01-11,4.700000,-2.7,14.6,0.0,3.3,0.700000,16.0,65.5,0.0,1.0,11.0,NaN
128023,296,북부산,2023-01-12,7.800000,-2.0,16.6,0.0,3.7,1.100000,27.0,75.0,0.0,1.0,12.0,NaN
128024,296,북부산,2023-01-13,14.900000,10.9,17.6,74.5,5.5,1.700000,86.0,93.3,0.0,1.0,13.0,NaN
128025,296,북부산,2023-01-14,10.600000,8.4,13.0,1.0,5.7,3.600000,75.0,82.9,0.0,1.0,14.0,NaN
128026,296,북부산,2023-01-15,6.400000,1.9,8.4,0.5,4.3,1.800000,63.0,79.9,0.0,1.0,15.0,NaN
154433,181,서청주,2023-05-01,13.600000,6.9,21.0,0.0,5.6,2.200000,20.0,55.3,0.0,5.0,1.0,NaN
154434,181,서청주,2023-05-02,16.000000,3.7,26.3,0.0,4.0,1.200000,15.0,46.8,0.0,5.0,2.0,NaN
154435,181,서청주,2023-05-03,18.800000,10.0,26.5,0.0,4.4,1.700000,18.0,50.9,0.0,5.0,3.0,NaN
154436,181,서청주,2023-05-04,20.100000,13.2,27.3,0.8,5.4,2.400000,43.0,66.4,0.0,5.0,4.0,NaN
154437,181,서청주,2023-05-05,19.600000,16.9,21.5,49.1,3.5,1.200000,83.0,93.0,0.0,5.0,5.0,NaN
159067,239,세종,2019-05-31,20.466667,13.7,24.1,0.2,3.3,1.333333,39.0,51.3,0.0,5.0,31.0,NaN
159068,239,세종,2019-06-01,17.400000,10.8,23.5,0.0,2.7,0.900000,44.0,69.9,0.0,6.0,1.0,NaN
159069,239,세종,2019-06-02,21.000000,13.5,28.0,0.0,3.2,1.100000,26.0,53.5,0.0,6.0,2.0,NaN
159070,239,세종,2019-06-03,22.200000,13.9,29.5,0.0,4.1,0.900000,25.0,47.0,0.0,6.0,3.0,NaN
159071,239,세종,2019-06-04,23.100000,16.3,30.9,0.0,3.1,1.200000,25.0,53.9,0.0,6.0,4.0,NaN

(11, 15)

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),월,일,실효습도
80474,106,동해,2016-01-01,6.4,0.5,11.6,0.0,5.3,1.7,18.0,35.9,0.0,1.0,1.0,NaN
80475,106,동해,2016-01-02,9.8,5.3,14.1,0.0,4.8,1.6,24.0,46.3,0.0,1.0,2.0,NaN
80476,106,동해,2016-01-03,9.9,5.3,14.1,0.0,3.4,1.3,41.0,64.0,0.0,1.0,3.0,NaN
132766,93,북춘천,2016-10-01,18.6,14.7,25.3,0.0,2.1,0.6,48.0,79.3,0.0,10.0,1.0,NaN
132767,93,북춘천,2016-10-02,17.0,15.6,19.4,31.5,4.4,0.7,78.0,89.0,0.0,10.0,2.0,NaN
132768,93,북춘천,2016-10-03,20.5,15.0,29.0,39.0,3.7,0.9,49.0,81.1,0.0,10.0,3.0,NaN
132769,93,북춘천,2016-10-04,18.3,11.4,26.3,0.0,4.5,1.5,42.0,72.4,0.0,10.0,4.0,NaN
132770,93,북춘천,2016-10-05,18.0,14.2,25.6,0.0,5.0,1.3,47.0,79.4,0.0,10.0,5.0,NaN
161479,90,속초,2016-01-01,3.6,-2.3,7.6,0.0,6.3,2.3,30.0,44.9,0.0,1.0,1.0,NaN
161480,90,속초,2016-01-02,8.4,5.0,11.5,0.0,8.0,3.1,38.0,50.4,0.0,1.0,2.0,NaN
161481,90,속초,2016-01-03,6.7,2.4,9.8,0.0,5.3,1.9,53.0,80.0,0.0,1.0,3.0,NaN

In [17]:
weather_df.isna().sum()

지점             0
지점명            0
일시             0
평균기온(°C)       0
최저기온(°C)       0
최고기온(°C)       0
일강수량(mm)       0
최대 풍속(m/s)     0
평균 풍속(m/s)     0
최소 상대습도(%)     0
평균 상대습도(%)     0
일 최심적설(cm)     0
월              0
일              0
실효습도          26
dtype: int64

In [18]:
# 산불데이터 시도 = 날씨데이터 지점명 매칭
# weather_df['지점명'].unique()
print(mt_fire['시도'].unique())
print(weather_df['지점명'].unique())

['경북' '전남' '대구' '강원' '부산' '경남' '경기' '충남' '충북' '인천' '울산' '전북' '서울' '광주'
 '대전' '세종' '제주']
['강릉' '강진군' '강화' '거제' '거창' '경주시' '고산' '고창' '고창군' '고흥' '광양시' '광주' '구미' '군산'
 '금산' '김해시' '남원' '남해' '대관령' '대구' '대전' '동두천' '동해' '목포' '문경' '밀양' '백령도' '보령'
 '보성군' '보은' '봉화' '부산' '부안' '부여' '북강릉' '북부산' '북창원' '북춘천' '산청' '상주' '서귀포'
 '서산' '서울' '서청주' '성산' '세종' '속초' '수원' '순창군' '순천' '안동' '양산시' '양평' '여수' '영광군'
 '영덕' '영월' '영주' '영천' '완도' '울릉도' '울산' '울진' '원주' '의령군' '의성' '이천' '인제' '인천'
 '임실' '장수' '장흥' '전주' '정선군' '정읍' '제주' '제천' '진도(첨찰산)' '진도군' '진주' '창원' '천안'
 '철원' '청송군' '청주' '추풍령' '춘천' '충주' '태백' '통영' '파주' '포항' '함양군' '합천' '해남' '홍성'
 '홍천' '흑산도']

In [19]:
sido_to_locs = {

    '강원': [
        '속초','북춘천','철원','대관령','춘천','북강릉','강릉','동해',
        '원주','영월','울진','울릉도','인제','홍천','태백','정선군'
    ],

    '경기': [
        '동두천','파주','수원','양평','이천'
    ],

    '인천': [
        '백령도','인천','강화'
    ],

    '서울': [
        '서울'
    ],

    '충북': [
        '충주','청주','서청주','제천','보은'
    ],

    '충남': [
        '서산','홍성','천안','보령','부여','금산'
    ],

    '대전': [
        '대전'
    ],

    '세종': [
        '세종'
    ],

    '경북': [
        '추풍령','안동','상주','포항','봉화','영주','문경',
        '청송군','영덕','의성','구미','영천','경주시'
    ],

    '전북': [
        '군산','전주','부안','임실','정읍','남원','장수',
        '고창','고창군'
    ],

    '전남': [
        '목포','여수','흑산도','완도','순천',
        '진도(첨찰산)','보성군','강진군','장흥',
        '해남','고흥','영광군','진도군'
    ],

    '대구': [
        '대구'
    ],

    '울산': [
        '울산'
    ],

    '경남': [
        '창원','북창원','통영','진주','김해시','양산시',
        '의령군','함양군','거창','합천','밀양',
        '산청','거제','남해'
    ],

    '광주': [
        '광주'
    ],

    '부산': [
        '부산','북부산'
    ],

    '제주': [
        '제주','고산','성산','서귀포'
    ]
}

In [20]:
loc_to_sido = {}
for sido,locs in sido_to_locs.items():
    # print(locs)
    for loc in locs:
        loc_to_sido[loc] = sido
        # print(loc_to_sido)


print(type(loc_to_sido))

<class 'dict'>

In [21]:
loc_to_sido

{'속초': '강원',
 '북춘천': '강원',
 '철원': '강원',
 '대관령': '강원',
 '춘천': '강원',
 '북강릉': '강원',
 '강릉': '강원',
 '동해': '강원',
 '원주': '강원',
 '영월': '강원',
 '울진': '강원',
 '울릉도': '강원',
 '인제': '강원',
 '홍천': '강원',
 '태백': '강원',
 '정선군': '강원',
 '동두천': '경기',
 '파주': '경기',
 '수원': '경기',
 '양평': '경기',
 '이천': '경기',
 '백령도': '인천',
 '인천': '인천',
 '강화': '인천',
 '서울': '서울',
 '충주': '충북',
 '청주': '충북',
 '서청주': '충북',
 '제천': '충북',
 '보은': '충북',
 '서산': '충남',
 '홍성': '충남',
 '천안': '충남',
 '보령': '충남',
 '부여': '충남',
 '금산': '충남',
 '대전': '대전',
 '세종': '세종',
 '추풍령': '경북',
 '안동': '경북',
 '상주': '경북',
 '포항': '경북',
 '봉화': '경북',
 '영주': '경북',
 '문경': '경북',
 '청송군': '경북',
 '영덕': '경북',
 '의성': '경북',
 '구미': '경북',
 '영천': '경북',
 '경주시': '경북',
 '군산': '전북',
 '전주': '전북',
 '부안': '전북',
 '임실': '전북',
 '정읍': '전북',
 '남원': '전북',
 '장수': '전북',
 '고창': '전북',
 '고창군': '전북',
 '목포': '전남',
 '여수': '전남',
 '흑산도': '전남',
 '완도': '전남',
 '순천': '전남',
 '진도(첨찰산)': '전남',
 '보성군': '전남',
 '강진군': '전남',
 '장흥': '전남',
 '해남': '전남',
 '고흥': '전남',
 '영광군': '전남',
 '진도군': '전남',
 '대구': '대구',
 '울산': '울산',
 '창원': '경남',
 '북창원': '경남',
 '통영': '경남',
 '진주': '경남',
 '김해시': '경남',
 '양산시': '경남',
 '의령군': '경남',
 '함양군': '경남',
 '거창': '경남',
 '합천': '경남',
 '밀양': '경남',
 '산청': '경남',
 '거제': '경남',
 '남해': '경남',
 '광주': '광주',
 '부산': '부산',
 '북부산': '부산',
 '제주': '제주',
 '고산': '제주',
 '성산': '제주',
 '서귀포': '제주'}

In [22]:
weather_df['시도'] = weather_df['지점명'].map(loc_to_sido) # 속초 : 강원 --> 변환 map

# 매핑 안 된 지점은 '기타' 처리
weather_df['시도'] = weather_df['시도'].astype(str)

# 확인
print(weather_df[['지점명', '시도']].head())
weather_df

  지점명  시도
5  강릉  강원
6  강릉  강원
7  강릉  강원
8  강릉  강원
9  강릉  강원

,지점,지점명,일시,평균기온(°C),최저기온(°C),최고기온(°C),일강수량(mm),최대 풍속(m/s),평균 풍속(m/s),최소 상대습도(%),평균 상대습도(%),일 최심적설(cm),월,일,실효습도,시도
5,105,강릉,2016-01-01,5.1,2.1,8.9,0.0,9.6,4.8,20.0,33.0,0.0,1.0,1.0,32.568148,강원
6,105,강릉,2016-01-02,9.1,5.5,11.2,0.0,9.5,4.9,35.0,43.8,0.0,1.0,2.0,34.257676,강원
7,105,강릉,2016-01-03,9.0,5.3,13.8,0.0,5.7,2.6,31.0,55.8,0.0,1.0,3.0,40.240365,강원
8,105,강릉,2016-01-04,7.4,3.3,12.0,0.0,6.9,3.4,13.0,33.8,0.0,1.0,4.0,37.708246,강원
9,105,강릉,2016-01-05,3.0,0.4,7.7,0.0,5.7,3.7,10.0,16.3,0.0,1.0,5.0,29.817512,강원
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349335,169,흑산도,2025-12-27,3.2,1.2,6.0,0.0,6.5,3.5,57.0,72.3,0.0,12.0,27.0,63.150884,전남
349336,169,흑산도,2025-12-28,7.8,3.4,14.2,0.4,7.1,4.7,47.0,72.1,0.0,12.0,28.0,63.619111,전남
349337,169,흑산도,2025-12-29,10.0,6.3,14.5,0.0,9.7,5.6,56.0,71.8,0.0,12.0,29.0,62.949797,전남
349338,169,흑산도,2025-12-30,4.8,3.5,6.5,0.0,11.9,9.2,45.0,56.5,0.0,12.0,30.0,58.328931,전남
349339,169,흑산도,2025-12-31,2.3,0.3,5.2,0.0,14.7,11.4,56.0,66.9,0.0,12.0,31.0,58.666097,전남

In [44]:
weather_df['일시'] = pd.to_datetime(weather_df['일시']).dt.date
mt_fire['일시'] = pd.to_datetime(mt_fire['일시']).dt.date
weather_df = weather_df.dropna(subset=['시도'])

weather_sido = (
    weather_df
    .groupby(['일시', '시도'])
    .agg({
        '평균기온(°C)': 'mean',
        '최고기온(°C)': 'max',
        '일강수량(mm)': 'mean',
        '평균 상대습도(%)': 'mean',
        '최대 풍속(m/s)': 'max',
        '평균 풍속(m/s)': 'mean',
        '최저기온(°C)': 'min',
        '일 최심적설(cm)' : 'max',
        '실효습도' : 'mean'
    })
    .reset_index()
)
weather_sido['일시'] = pd.to_datetime(weather_sido['일시'])
mt_fire['일시'] = pd.to_datetime(mt_fire['일시'])

print(weather_sido)
weather_loc_mtfire = pd.merge(weather_sido,mt_fire,how='inner',right_on=['일시','시도'], left_on=['일시','시도'])
weather_loc_mtfire

              일시   시도  평균기온(°C)  최고기온(°C)  일강수량(mm)  평균 상대습도(%)  최대 풍속(m/s)  \
0     2016-01-01  nan  1.550000      10.2       0.0   78.950000         5.2
1     2016-01-01   강원  1.160000      11.6       0.0   61.560000        11.0
2     2016-01-01   경기 -0.300000       6.5       0.0   79.280000         3.8
3     2016-01-01   경남  1.764286      10.3       0.0   64.828571         5.1
4     2016-01-01   경북  0.384615       9.3       0.0   65.453846         8.6
...          ...  ...       ...       ...       ...         ...         ...
64503 2025-12-31   전남 -0.550000       5.2       0.0   52.950000        14.7
64504 2025-12-31   전북 -2.501235       1.1       0.0   54.011111         9.0
64505 2025-12-31   제주  5.075000      12.4       0.0   55.400000        15.7
64506 2025-12-31   충남 -3.183333       0.8       0.1   52.116667         7.0
64507 2025-12-31   충북 -4.640000      -0.9       0.0   45.420000         6.9

       평균 풍속(m/s)  최저기온(°C)  일 최심적설(cm)       실효습도
0        1.300000      -6.1         0.0  63.292918
1        2.146667      -9.0         0.0  54.602813
2        0.800000      -6.9         0.0  62.539044
3        1.121429      -8.2         0.0  51.543800
4        1.953846     -10.4         0.0  52.291724
...           ...       ...         ...        ...
64503    4.433333      -5.6         0.0  52.386359
64504    2.655556     -10.0         0.0  55.471153
64505    5.250000       0.8         0.0  49.192290
64506    2.350000      -7.8         0.1  57.274159
64507    2.200000     -11.1         0.0  53.885506

[64508 rows x 11 columns]

,일시,시도,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),일 최심적설(cm),...,진화종료시간_시간,발생장소_관서,발생장소_시군구,발생장소_읍면,발생장소_동리,발생원인_구분,발생원인_세부원인,발생원인_기타,피해면적_합계,산불발생
0,2016-01-03,경북,4.376923,16.3,0.0000,72.415385,6.5,1.184615,-6.600000,0.0,...,16:20,경북,영양,청기,상청,입,기타(직접입력),입산자 실화추정,0.50,1
1,2016-01-05,경기,-1.940000,3.1,0.0000,38.740000,5.6,1.780000,-7.333333,0.0,...,17:30,경기,성남 수정,NaN,금토,기,무속행위,무속행위,0.10,1
2,2016-01-06,강원,-1.433333,9.4,0.0000,50.800000,7.9,2.080000,-10.500000,0.0,...,16:30,강원,고성,거진,거진,담,기타(직접입력),담뱃불 실화,0.06,1
3,2016-01-06,경북,0.084615,7.0,0.0000,46.515385,9.6,2.976923,-9.800000,0.0,...,21:20,경북,울진,금강송,광회,NaN,주택화재비화,주택내 불씨취급 부주의,0.30,1
4,2016-01-08,경북,-1.084615,5.9,0.0000,43.684615,9.9,3.223077,-10.300000,0.0,...,14:15,경북,칠곡,동명,금암,쓰,기타(직접입력),쓰레기 소각,0.20,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5271,2025-12-29,강원,4.631250,12.2,1.0375,69.200000,9.7,2.443750,-3.800000,13.0,...,22:35,강원,고성,거진,화포,기,기타(직접입력),원인미상,0.36,1
5272,2025-12-29,강원,4.631250,12.2,1.0375,69.200000,9.7,2.443750,-3.800000,13.0,...,23:51,강원,강릉,연곡,신왕,입,기타(직접입력),입산자 실화추정,2.10,1
5273,2025-12-30,대구,3.500000,7.4,0.0000,36.000000,5.5,2.800000,-0.100000,0.0,...,05:47,대구,동,NaN,신용,기,기타(직접입력),물탱크 모터 발화,0.02,1
5274,2025-12-30,전남,3.566667,10.3,0.0000,48.941667,11.9,3.408333,-4.100000,0.0,...,12:40,전남,장흥,용산,녹원,기,기타(직접입력),태양광 전선 노출에 의한 스파크 추정,0.15,1
5275,2025-12-31,경북,-3.292308,2.4,0.0000,38.430769,9.0,2.869231,-11.400000,0.0,...,20:30,경북,안동,임동,대곡,기,기타(직접입력),원인미상,0.30,1

In [45]:
fire_daily = (
    mt_fire
    .groupby(['시도','일시','발생장소_시군구'])
    .size()
    .reset_index(name='fire_count')
)

fire_daily['fire'] = 1
fire_daily = fire_daily[['시도','일시','fire','발생장소_시군구']]

fire_daily

      시도         일시  fire 발생장소_시군구
0     강원 2016-01-06     1       고성
1     강원 2016-01-12     1       양구
2     강원 2016-01-13     1       원주
3     강원 2016-01-19     1       강릉
4     강원 2016-01-22     1       춘천
...   ..        ...   ...      ...
5100  충북 2025-11-10     1       괴산
5101  충북 2025-11-10     1       진천
5102  충북 2025-11-24     1       단양
5103  충북 2025-12-07     1       제천
5104  충북 2025-12-08     1       충주

[5105 rows x 4 columns]

In [46]:
fire_daily['시도'].value_counts().sum()

np.int64(5105)

In [47]:
fire_daily

      시도         일시  fire 발생장소_시군구
0     강원 2016-01-06     1       고성
1     강원 2016-01-12     1       양구
2     강원 2016-01-13     1       원주
3     강원 2016-01-19     1       강릉
4     강원 2016-01-22     1       춘천
...   ..        ...   ...      ...
5100  충북 2025-11-10     1       괴산
5101  충북 2025-11-10     1       진천
5102  충북 2025-11-24     1       단양
5103  충북 2025-12-07     1       제천
5104  충북 2025-12-08     1       충주

[5105 rows x 4 columns]

In [48]:
# weather_sido = weather_sido.drop('지점명',axis=1)
# weather_sido

In [49]:
fire_daily = fire_daily.drop('발생장소_시군구',axis=1)

In [50]:
full_dates = pd.date_range(
    start=weather_loc_mtfire['일시'].min(),
    end=weather_loc_mtfire['일시'].max(),
    freq='D'
)

sido_list = weather_loc_mtfire['시도'].unique()
# print(sido_list)
base_df = (
    pd.MultiIndex
    .from_product([sido_list, full_dates], names=['시도','일시'])
    .to_frame(index=False)
)

print(base_df)
base_df = base_df.merge(
    fire_daily,
    on=['시도','일시'],
    how='left'
)

base_df['fire'] = base_df['fire'].fillna(0).astype(int)
base_df
base_df = base_df.merge(
    weather_sido,
    on=['시도', '일시'],
    how='left'
)

base_df

       시도         일시
0      경북 2016-01-03
1      경북 2016-01-04
2      경북 2016-01-05
3      경북 2016-01-06
4      경북 2016-01-07
...    ..        ...
62062  제주 2025-12-27
62063  제주 2025-12-28
62064  제주 2025-12-29
62065  제주 2025-12-30
62066  제주 2025-12-31

[62067 rows x 2 columns]

,시도,일시,fire,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),일 최심적설(cm),실효습도
0,경북,2016-01-03,1,4.376923,16.3,0.0,72.415385,6.5,1.184615,-6.6,0.0,59.201499
1,경북,2016-01-04,0,5.192308,12.9,0.0,50.807692,8.3,2.715385,-6.2,0.0,55.198808
2,경북,2016-01-05,0,0.423077,7.0,0.0,33.076923,8.1,2.646154,-7.0,0.0,46.443746
3,경북,2016-01-06,1,0.084615,7.0,0.0,46.515385,9.6,2.976923,-9.8,0.0,43.977776
4,경북,2016-01-07,0,-0.030769,6.4,0.0,44.192308,8.1,3.092308,-9.2,0.0,41.731961
...,...,...,...,...,...,...,...,...,...,...,...,...
63262,제주,2025-12-27,0,4.200000,9.4,0.0,59.325000,6.1,2.625000,-2.8,0.0,54.115659
63263,제주,2025-12-28,0,8.950000,13.7,0.0,53.875000,12.7,2.800000,1.0,0.0,51.877249
63264,제주,2025-12-29,0,12.325000,17.3,0.0,60.600000,11.5,4.400000,5.0,0.0,52.197272
63265,제주,2025-12-30,0,8.325000,15.8,0.0,51.725000,10.3,3.700000,3.6,0.0,49.414664
63266,제주,2025-12-31,0,5.075000,12.4,0.0,55.400000,15.7,5.250000,0.8,0.0,49.192290

In [51]:
base_df[base_df['일 최심적설(cm)']>1]

,시도,일시,fire,평균기온(°C),최고기온(°C),일강수량(mm),평균 상대습도(%),최대 풍속(m/s),평균 풍속(m/s),최저기온(°C),일 최심적설(cm),실효습도
25,경북,2016-01-28,0,-0.923077,6.6,2.684615,64.253846,6.1,0.923077,-12.3,1.6,47.312925
26,경북,2016-01-29,0,1.561538,6.5,8.730769,89.484615,10.2,1.500000,-2.2,2.7,58.925954
55,경북,2016-02-26,0,2.253846,8.9,0.930769,67.684615,7.0,1.976923,-6.0,1.2,44.833505
354,경북,2016-12-14,0,2.138462,8.5,1.446154,78.346154,7.8,2.361538,-2.0,1.3,57.927388
355,경북,2016-12-15,0,-0.661538,5.0,0.000000,48.130769,9.2,3.461538,-7.9,1.3,52.885110
...,...,...,...,...,...,...,...,...,...,...,...,...
62937,제주,2025-02-05,0,2.175000,6.3,2.500000,63.725000,24.5,8.200000,-1.3,1.5,58.339929
62938,제주,2025-02-06,0,2.375000,6.5,1.450000,63.550000,17.3,4.775000,-1.5,1.4,57.478204
62939,제주,2025-02-07,0,1.675000,7.0,3.250000,67.625000,27.9,9.100000,-2.7,2.8,57.523958
62940,제주,2025-02-08,0,0.750000,3.8,1.600000,65.275000,23.5,6.750000,-2.4,5.8,57.531291
62956,제주,2025-02-24,0,3.550000,10.3,0.125000,54.625000,19.9,6.125000,-0.6,1.5,49.016142

In [52]:
base_df['fire'].value_counts()

fire
0    58162
1     5105
Name: count, dtype: int64

In [57]:
base_df = base_df.dropna()

In [58]:
base_df.to_csv('머신러닝용_final.csv',encoding='utf-8')